/**
 * input.js — Keyboard and D-pad input handling
 *
 * Binds input sources to a single direction callback.
 * All handlers are passive where possible; D-pad buttons carry ARIA labels.
 *
 * v2 stub: bindTouch() is exported but not wired in v1 — see comment below.
 */

/** @typedef {'UP'|'DOWN'|'LEFT'|'RIGHT'} Direction */

const KEY_MAP = {
  ArrowUp:    'UP',
  ArrowDown:  'DOWN',
  ArrowLeft:  'LEFT',
  ArrowRight: 'RIGHT',
  w: 'UP', W: 'UP',
  s: 'DOWN', S: 'DOWN',
  a: 'LEFT', A: 'LEFT',
  d: 'RIGHT', D: 'RIGHT',
};

/** Stored so callers can call unbindKeyboard() if needed */
let _keyHandler = null;

/**
 * Attaches a keydown listener for arrow keys and WASD.
 * Also intercepts arrow key scroll — prevents page jumping during play.
 *
 * @param {(dir: Direction) => void} onDirection
 */
export function bindKeyboard(onDirection) {
  _keyHandler = (event) => {
    const dir = KEY_MAP[event.key];
    if (!dir) return;
    // Prevent arrow keys from scrolling the page while the game is active
    event.preventDefault();
    onDirection(dir);
  };
  window.addEventListener('keydown', _keyHandler);
}

/** Removes the keyboard listener. Call on game over / teardown. */
export function unbindKeyboard() {
  if (_keyHandler) {
    window.removeEventListener('keydown', _keyHandler);
    _keyHandler = null;
  }
}

/**
 * Wires up D-pad button elements to the direction callback.
 * Expects the container to have buttons with `data-dir` attributes.
 *
 * Required HTML structure (generated by ui.js or hand-authored):
 *   <div id="dpad">
 *     <button data-dir="UP"    aria-label="Move up">▲</button>
 *     <button data-dir="LEFT"  aria-label="Move left">◀</button>
 *     <button data-dir="DOWN"  aria-label="Move down">▼</button>
 *     <button data-dir="RIGHT" aria-label="Move right">▶</button>
 *   </div>
 *
 * Uses both `click` and `touchstart` to avoid 300ms tap delay on mobile.
 *
 * @param {HTMLElement} container
 * @param {(dir: Direction) => void} onDirection
 */
export function bindDpad(container, onDirection) {
  container.querySelectorAll('button[data-dir]').forEach((btn) => {
    const dir = /** @type {Direction} */ (btn.dataset.dir);
    if (!dir) return;

    btn.addEventListener('click', () => onDirection(dir));

    // touchstart fires immediately, avoiding tap delay; preventDefault stops
    // the synthetic click event that would fire 300ms later on iOS
    btn.addEventListener('touchstart', (e) => {
      e.preventDefault();
      onDirection(dir);
    }, { passive: false });
  });
}

/**
 * v2 STUB — Touch/swipe support.
 *
 * Not wired in v1. Reason: iOS Safari requires `{ passive: false }` on
 * touchstart to call preventDefault() and suppress scroll, which conflicts
 * with some WKWebView contexts. D-pad is the reliable v1 path.
 *
 * To activate in v2: call bindTouch(canvas, onDirection) after bindDpad().
 * The callback signature is identical so engine.js needs no changes.
 *
 * @param {HTMLElement} _element - Canvas or overlay to listen on
 * @param {(dir: Direction) => void} _onDirection
 */
export function bindTouch(_element, _onDirection) {
  // v2: implement touchstart/touchend delta detection here
  // Minimum swipe threshold: 30px (avoids accidental triggers)
  // Must call e.preventDefault() on touchstart with { passive: false }
  console.warn('bindTouch() is a v2 stub — swipe support not yet implemented.');
}